/** Types for the vendored SCIM (satisfactory-calculator.com Interactive Map)
 * layer taxonomy (`src/data/scimLayers.json`, generated by
 * `scripts/build_scim_map_data.py`) and its static world geometry
 * (`/assets/scim/static-layers.json`). */

/** How live FRM features are matched onto a SCIM layer. */
export interface ScimLayerMatch {
  kind: 'pickup' | 'node' | 'well' | 'geyser';
  /** Pickup layers: our feature `meta.kind` slug. */
  pickup?: string;
  /** Node/well layers: our feature `meta.resource` slug. */
  resource?: string;
  /** Node/well/geyser layers: `impure` | `normal` | `pure`. */
  purity?: string;
}

export interface ScimLayer {
  id: string;
  name: string;
  /** Pin ring / anchor color (resource color). */
  outsideColor: string | null;
  /** Pin head fill (purity color for nodes, white for pickups). */
  insideColor: string | null;
  /** Local public path of the layer icon, if any. */
  icon: string | null;
  purity: 'impure' | 'normal' | 'pure' | null;
  /** True when the data is vendored geometry (FRM has no live endpoint). */
  static: boolean;
  /** Marker count in the vendored data (0 for live-only layers). */
  count: number;
  match?: ScimLayerMatch;
}

export interface ScimGroup {
  name: string;
  type: string | null;
  layers: ScimLayer[];
}

export interface ScimCategory {
  id: string;
  name: string;
  groups: ScimGroup[];
}

/** A cave outline: main polygon, optional holes, optional entrance lines (cm). */
export interface ScimCave {
  points: [number, number][];
  holes?: [number, number][][];
  entrances?: number[][][];
}

/** A road path (cm) with an optional display name and corridor width (cm). */
export interface ScimRoad {
  points: [number, number][];
  corridor?: number;
  name?: string;
}

/** Static world geometry vendored from SCIM; keys are layer ids. */
export interface ScimStaticLayers {
  /** Point layers: `[x, y, z][]` in cm. */
  paleBerry?: [number, number, number][];
  berylNut?: [number, number, number][];
  baconAgaric?: [number, number, number][];
  sporeFlowers?: [number, number, number][];
  pillars?: [number, number, number][];
  smallRocks?: [number, number, number][];
  largeRocks?: [number, number, number][];
  spawn?: { x: number; y: number; radius: number }[];
  worldBorder?: [number, number][];
  caves?: Record<string, ScimCave>;
  roads?: Record<string, ScimRoad>;
}
