import type { Position } from '../types/world';
import { toLatLng } from './mapCoords';

/**
 * Building footprint outlines, from SCIM's detailed models
 * (`/assets/scim/building-models.json`, generated by
 * `scripts/build_scim_building_data.py`).
 *
 * A model's `forms` are outline polygons in cm relative to the building
 * center, drawn for a building facing rotation 0; FRM reports each building's
 * yaw in degrees, so the points are rotated around the center and translated
 * to the building's world position before conversion to map coordinates.
 */

export interface BuildingForm {
  points: [number, number][];
  holes?: [number, number][][];
}

export interface BuildingModel {
  name?: string;
  category?: string;
  /** SCIM map color/opacity/weight for the outline. */
  color?: string;
  opacity?: number;
  weight?: number;
  /** Generic footprint in meters (rectangle fallback). */
  width?: number;
  length?: number;
  /** Point multiplier for the detailed forms. */
  scale?: number;
  forms?: BuildingForm[];
}

/** The vendored asset: short UE class name → model. */
export type BuildingModels = Record<string, BuildingModel>;

/** One Leaflet polygon: outer ring plus optional hole rings (latlng). */
export type OutlineRings = [number, number][][];

function ring(
  points: [number, number][],
  center: Position,
  scale: number,
  cos: number,
  sin: number,
): [number, number][] {
  return points.map(([px, py]) => {
    const x = px * scale;
    const y = py * scale;
    return toLatLng({
      x: center.x + x * cos - y * sin,
      y: center.y + x * sin + y * cos,
      z: 0,
    });
  });
}

/**
 * The rotated footprint polygons for a building, or null when the model has
 * neither a detailed outline nor a generic width × length footprint.
 */
export function buildingOutline(
  model: BuildingModel | undefined,
  center: Position,
  rotationDeg: number,
): OutlineRings[] | null {
  if (!model) return null;
  const theta = (rotationDeg * Math.PI) / 180;
  const cos = Math.cos(theta);
  const sin = Math.sin(theta);
  if (model.forms?.length) {
    const scale = model.scale ?? 1;
    return model.forms.map((form) => [
      ring(form.points, center, scale, cos, sin),
      ...(form.holes ?? []).map((hole) => ring(hole, center, scale, cos, sin)),
    ]);
  }
  if (model.width && model.length) {
    // Meters → cm half-extents; width spans x, length spans y (SCIM convention).
    const w = (model.width * 100) / 2;
    const l = (model.length * 100) / 2;
    const rect: [number, number][] = [
      [-w, -l],
      [w, -l],
      [w, l],
      [-w, l],
    ];
    return [[ring(rect, center, 1, cos, sin)]];
  }
  return null;
}
